### ISSUE TITLE
yml文件中配置mybatis.mapper-locations，启动报错

### ISSUE THREAD

**Issue by singleJava** [helloworlde/SpringBoot-DynamicDataSource#9]
Caused by: org.springframework.core.NestedIOException: Failed to parse mapping resource: 'ServletContext resource [/classpath*:mappers/*Mapper.xml]'; nested exception is java.io.FileNotFoundException: Could not open ServletContext resource [/classpath*:mappers/*Mapper.xml]
	at org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory(SqlSessionFactoryBean.java:523)
	at org.mybatis.spring.SqlSessionFactoryBean.afterPropertiesSet(SqlSessionFactoryBean.java:380)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1753)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1690)
	... 55 common frames omitted
Caused by: java.io.FileNotFoundException: Could not open ServletContext resource [/classpath*:mappers/*Mapper.xml]
	at org.springframework.web.context.support.ServletContextResource.getInputStream(ServletContextResource.java:159)
	at org.mybatis.spring.SqlSessionFactoryBean.buildSqlSessionFactory(SqlSessionFactoryBean.java:519)
	... 58 common frames omitted

**Comment by helloworlde** [comment]
Please reference how to set configuration correctly in yaml file in spring boot document
